### ISSUE TITLE
Landing page height

### ISSUE THREAD

**Issue by tdutrion** [scotlandphp/website#2]
While accessing the main page (`index.html`) from a screen in landscape position, with a relatively small screen, the first section can not be seen entirely.

This bug comes from the following css:

``` css
#main>section.one {
    background-color: #81918E;
    background-image: url(landscape.jpg);
    height: 100vh;
}
```

Changing the `height` to `min-height` should fix the bug.
